services:
  - type: web
    name: my-flask-app
    env: docker
    plan: free
    branch: main
    buildCommand : "pip install requirements.txt"
    startCommand : "gunicorn app:app"
    autoDeploy: false
